<a href="https://colab.research.google.com/github/shiviverma916/myfile/blob/main/FSDS_Collaborative_Filtering_Systems.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import pandas as pd

from pandas import Series, DataFrame
from sklearn.linear_model import LogisticRegression

import warnings
warnings.filterwarnings('ignore')

In [2]:
bank_full = pd.read_csv('bank_full_w_dummy_vars.csv')
bank_full.head()

,age,job,marital,education,default,balance,housing,loan,contact,day,...,job_unknown,job_retired,job_services,job_self_employed,job_unemployed,job_maid,job_student,married,single,divorced
0,58,management,married,tertiary,no,2143,yes,no,unknown,5,...,0,0,0,0,0,0.0,0.0,1.0,0.0,0.0
1,44,technician,single,secondary,no,29,yes,no,unknown,5,...,0,0,0,0,0,0.0,0.0,0.0,1.0,1.0
2,33,entrepreneur,married,secondary,no,2,yes,yes,unknown,5,...,0,0,0,0,0,0.0,0.0,1.0,0.0,0.0
3,47,blue-collar,married,unknown,no,1506,yes,no,unknown,5,...,0,0,0,0,0,0.0,0.0,1.0,0.0,0.0
4,33,unknown,single,unknown,no,1,no,no,unknown,5,...,1,0,0,0,0,0.0,0.0,0.0,1.0,1.0

In [3]:
bank_full.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8550 entries, 0 to 8549
Data columns (total 37 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   age                           8550 non-null   int64
 1   job                           8550 non-null   object
 2   marital                       8550 non-null   object
 3   education                     8550 non-null   object
 4   default                       8550 non-null   object
 5   balance                       8550 non-null   int64
 6   housing                       8550 non-null   object
 7   loan                          8550 non-null   object
 8   contact                       8550 non-null   object
 9   day                           8550 non-null   int64
 10  month                         8550 non-null   object
 11  duration                      8550 non-null   int64
 12  campaign                      8550 non-null   int64
 13  pdays                         8550 non-null   int64
 14  previous                      8550 non-null   int64
 15  poutcome                      8550 non-null   object
 16  y                             8550 non-null   object
 17  y_binary                      8550 non-null   int64
 18  housing_loan                  8550 non-null   int64
 19  credit_in_default             8550 non-null   int64
 20  personal_loans                8550 non-null   int64
 21  prev_failed_to_subscribe      8550 non-null   int64
 22  prev_subscribed               8550 non-null   int64
 23  job_management                8550 non-null   int64
 24  job_tech                      8550 non-null   int64
 25  job_entrepreneur              8550 non-null   int64
 26  job_bluecollar                8550 non-null   int64
 27  job_unknown                   8550 non-null   int64
 28  job_retired                   8550 non-null   int64
 29  job_services                  8550 non-null   int64
 30  job_self_employed             8550 non-null   int64
 31  job_unemployed                8550 non-null   int64
 32  job_maid                      8549 non-null   float64
 33  job_student                   8549 non-null   float64
 34  married                       8549 non-null   float64
 35  single                        8549 non-null   float64
 36  divorced                      8549 non-null   float64
dtypes: float64(5), int64(22), object(10)
memory usage: 2.4+ MB

In [5]:
from sklearn import preprocessing

le = preprocessing.LabelEncoder()

bank_full = bank_full.apply(le.fit_transform)
bank_full.head()

,age,job,marital,education,default,balance,housing,loan,contact,day,...,job_unknown,job_retired,job_services,job_self_employed,job_unemployed,job_maid,job_student,married,single,divorced
0,38,4,1,2,0,2210,1,0,0,2,...,0,0,0,0,0,0,0,1,0,0
1,24,9,2,1,0,603,1,0,0,2,...,0,0,0,0,0,0,0,0,1,1
2,13,2,1,1,0,576,1,1,0,2,...,0,0,0,0,0,0,0,1,0,0
3,27,1,1,3,0,1886,1,0,0,2,...,0,0,0,0,0,0,0,1,0,0
4,13,11,2,3,0,575,0,0,0,2,...,1,0,0,0,0,0,0,0,1,1

In [6]:
bank_full.columns

Index(['age', 'job', 'marital', 'education', 'default', 'balance', 'housing',
       'loan', 'contact', 'day', 'month', 'duration', 'campaign', 'pdays',
       'previous', 'poutcome', 'y', 'y_binary                    ',
       'housing_loan                ', 'credit_in_default', 'personal_loans',
       'prev_failed_to_subscribe    ', 'prev_subscribed             ',
       'job_management              ', 'job_tech                    ',
       'job_entrepreneur            ', 'job_bluecollar              ',
       'job_unknown                 ', 'job_retired                 ',
       'job_services                ', 'job_self_employed           ',
       'job_unemployed              ', 'job_maid                    ',
       'job_student                 ', 'married                     ',
       'single                      ', 'divorced                    '],
      dtype='object')

In [7]:
new_bank_full= bank_full.loc[:,'housing_loan                ':'divorced                    ']

In [ ]:
new_bank_full

,housing_loan,credit_in_default,personal_loans,prev_failed_to_subscribe,prev_subscribed,job_management,job_tech,job_entrepreneur,job_bluecollar,job_unknown,job_retired,job_services,job_self_employed,job_unemployed,job_maid,job_student,married,single,divorced
0,1,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,1,0,0
1,1,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,1,1
2,1,0,1,0,0,0,0,1,0,0,0,0,0,0,0,0,1,0,0
3,1,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,1,0,0
4,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,1,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
45206,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,1,0,0
45207,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0
45208,0,0,0,0,1,0,0,0,0,0,1,0,0,0,0,0,1,0,0
45209,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,1,0,0
45210,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,1,0,0

In [8]:
bank_full['y']

0       0
1       0
2       0
3       0
4       0
       ..
8545    0
8546    0
8547    0
8548    0
8549    0
Name: y, Length: 8550, dtype: int64

In [9]:
X = new_bank_full
y=bank_full['y']

In [10]:
LogReg = LogisticRegression()
LogReg.fit(X, y)

LogisticRegression()

In [11]:

new_user = np.array([0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1]).reshape(1, -1)
y_pred = LogReg.predict(new_user)
y_pred

array([0])

In [12]:
y_pred = LogReg.predict(X)
y_pred

array([0, 0, 0, ..., 0, 0, 0])

In [13]:
from sklearn.metrics import classification_report

print(classification_report(y, y_pred))

              precision    recall  f1-score   support

           0       0.97      1.00      0.98      8271
           1       0.00      0.00      0.00       279

    accuracy                           0.97      8550
   macro avg       0.48      0.50      0.49      8550
weighted avg       0.94      0.97      0.95      8550

In [14]:
y.value_counts()

y
0    8271
1     279
Name: count, dtype: int64